### PR TITLE
lk2nd: display: panel: generated: Add hx8394a_720p_video for vivo,pd1410

### PR DESCRIPTION
**Pull request by zhangzqs**
The `vivo-pd1410` device (Vivo Y27L / Y627 / Y927) added in #721 uses the `hx8394a_720p_video` panel, but the generated panel driver was not included alongside the device node. As a result, the lk1st build command documented in `msm8916-vivo-cdp-1.dts` for this device fails to link:

```
make -j$(nproc) TOOLCHAIN_PREFIX=arm-none-eabi- lk1st-msm8916 \
    LK2ND_DISPLAY=hx8394a_720p_video \
    LK2ND_BUNDLE_DTB=msm8916-vivo-cdp-1.dtb \
    LK2ND_COMPATIBLE=vivo,pd1410
```

```
undefined reference to `panel_hx8394a_720p_video_select'
```

lk2nd's `oem_panel.c` selects the panel via `panel_select(LK2ND_DISPLAY)`, which expands to `panel_hx8394a_720p_video_select()`. This function is provided by the generated panel header, so the header is required — the gcdb `panel_hx8394a_720p_video.h` is filtered out by `lk2nd/display/panel/rules.mk` and does not participate in the build.

This change adds the generated `lk_panel_hx8394a_720p_video.h` driver and registers it in `panels.h`.

### Verification

Boot-tested on Vivo Y927 (PD1410V). The lk1st build command above now links successfully and produces `emmc_appsboot.mbn`. The panel command sequences and `panel_hx8394a_720p_video_select` are confirmed present in the resulting binary.

### Related

- This is the panel driver part of #708; the `vivo-pd1410` device node itself was already merged via #721.
- Fixes the build regression introduced by #721.

### CODE REVIEW

**Comment by zhangzqs** [comment]
efe9c580da7de0f900e83a7b7fb497c0

**Comment by TravMurav** [comment]
Thanks!
